import { ENV } from './constants'
import { screen } from './screens'
import { HomeStack } from '../navigation/stacks/HomeStack'
import { HomeScreen } from '../screens/HomeScreen'
import { UploadVideo } from '../screens/Upload/UploadVideo'
import { UsersScreen } from '../screens/Shared/UsersScreen'
import { VideoScreen } from '../screens/Shared/VideoScreen'
import { AccountStack } from '../navigation/stacks/AccountStack'
import { FriendsStack } from '../navigation/stacks/FriendsStack'
import { AccountScreen } from '../screens/Account/AccountScreen'
import { FriendsScreen } from '../screens/FriendsScreen'
import { ThemeProvider } from '../context/ThemeProvider'
import { FollowedScreen } from '../screens/Shared/FollowedScreen'
import { RootNavigation } from '../navigation/RootNavigation'
import { SettingsScreen } from '../screens/Account/SettingsScreen'
import { FollowersScreen } from '../screens/Shared/FollowersScreen'
import { UploadVideoStack } from '../navigation/stacks/UploadVideoStack'
import { ChangeNameScreen } from '../screens/Account/ChangeNameScreen'
import { ChangeDescription } from '../screens/Account/ChangeDescription'
import { NotificationsStack } from '../navigation/stacks/NotificationsStack'
import { PublishVideoScreen } from '../screens/Upload/PublishVideoScreen'
import { getNavigationTheme } from './navigation-theme'
import { NotificationsScreen } from '../screens/NotificationsScreen'
import { ChangeWebSiteScreen } from '../screens/Account/ChangeWebSiteScreen'
import { VideoFavoritesScreen } from '../screens/Shared/VideoFavoritesScreen'
import { VideoPublishedScreen } from '../screens/Shared/VideoPublishedScreen'
import { ChangeInstagramScreen } from '../screens/Account/ChangeInstagramScreen'

import AuthScreen from '../screens/Auth/AuthScreen'
import LoginEmailScreen from '../screens/Auth/LoginEmailScreen'
import RegisterEmailScreen from '../screens/Auth/RegisterEmailScreen'

export { ThemeProvider, RootNavigation, AuthScreen, getNavigationTheme, ChangeNameScreen, SettingsScreen, RegisterEmailScreen, LoginEmailScreen, screen, ENV, HomeScreen, HomeStack, FriendsScreen, FriendsStack, UploadVideo, UploadVideoStack, NotificationsScreen, NotificationsStack, AccountScreen, AccountStack, PublishVideoScreen, ChangeDescription, ChangeInstagramScreen, ChangeWebSiteScreen, VideoFavoritesScreen, VideoPublishedScreen, UsersScreen, VideoScreen, FollowedScreen, FollowersScreen }