# Generated by Django 4.1.4 on 2022-12-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='sharedCounter',
            new_name='shareCounter',
        ),
        migrations.AddField(
            model_name='video',
            name='music',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
