# Generated by Django 4.1.4 on 2022-12-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_rename_sharedcounter_video_sharecounter_video_music_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='commentsCounter',
            field=models.IntegerField(default=0),
        ),
    ]
